### PR TITLE
HTML improvements

### PR DESCRIPTION
**Pull request by Moskito89**
Even little things count. 😄 This pull request is to improve the HTML of the index.html in a few places.

### CODE REVIEW

**Comment by SimonFrings** [comment]
> Even little things count. 😄

@Moskito89 You're absolutely right, thanks for opening this up 👍

You used two commits for this, maybe it is worth to squash these together into one, what do you think?

**Comment by Moskito89** [comment]
Correct, I used two commits as they were thematically two different actions. From my point of view, this makes the changes more comprehensible... Do you have specific rules for this repository regarding the commits?

**Comment by SimonFrings** [comment]
We don't have any specific rules for this, we just use whatever feels more right. For smaller adjustments, we often use only one commit and then name it accordingly to the work done in the PR. Here it could be named something like "Clean up HTML structure ". 

We try to go for more commits if the diff gets too big or addresses different topics. This can then improve the overall pull request overview.

This PR doesn't introduce too many changes so I'd suggest changing it to one commit instead of two 👍

**Comment by Moskito89** [comment]
I'm okay with that! :-) But I'm not sure if the squash worked correctly, guess it's worse now... :-(

**Comment by SimonFrings** [comment]
@Moskito89 Maybe this helps: https://www.internalpointers.com/post/squash-commits-into-one-git

**Comment by Moskito89** [comment]
Thanks @SimonFrings, I tried to follow these steps but ended up with two commits and don't know why... Maybe this is some kind of chicken egg problem; never done › no experience › never done.

**Comment by SimonFrings** [comment]
@Moskito89 Yeah, I get that. As far as I see it, we have a few options here. I'd like to hear your opinion on this:

1. I can pull you current changes and open a second pull request with the repaired commit history. This one would then close this pull request once merged. I'm not a big fan of this method, as it feels like hijacking your work, but I would of course refer to this ticket and give you credit for all your work.

2. We can also take a look at this together, either via writing in here or we schedule a short zoom call where we go over the most important steps to squash your commit history via git commands. 

I would leave this decision up to you, happy to hear your thoughts! :)

**Comment by Moskito89** [comment]
Option 2 sounds good! It's always a good idea to learn something new. I'll send you an email so we can coordinate. :-)

**Review by clue — APPROVED** [review]
@Moskito89 Thanks for looking into this and good teamwork with @SimonFrings, keep it up and let's get this shipped! :+1:

**Pull request merged**
